### ISSUE TITLE
Application crash when click on Custom native ad

### ISSUE THREAD

**Issue by mArm-ch** [teads/TeadsSDK-iOS#22] opened 2015-11-06 14:11 UTC
The application crashes when I click on a native ad video while playing.
It tries to open the ad url with the method : 
[ApplicationController teads_presentModalViewController:animated:]

The methods exists in the SDK (grep -r 'teads_presentModalViewController) but seems to be called on the bad controller.
There is no documentation on ads click event.

**Comment by ibrahimennafaa** [comment] 2015-11-06 14:55
Hi,

The [wiki documentation](https://github.com/teads/TeadsSDK-iOS/wiki/Xcode-Integration#incorporate-the-teads-ios-sdk) tells to integrate the TeadsSDKBundle as well. Inside there is the inApp browser XIB which is used to display advertiser website when we tap on the ad.

Did you integrate the Bundle alongside the framework ?

Best,
Ibrahim

**Comment by mArm-ch** [comment] 2015-11-06 15:03
Yes I did

**Comment by ibrahimennafaa** [comment] 2015-11-06 15:05
Still crashing ? do you have the crash log ?

**Comment by mArm-ch** [comment] 2015-11-06 15:12
-[ApplicationController teads_presentModalViewController:animated:]: unrecognized selector sent to instance 0x145675c60
2015-11-06 16:12:34.072 SwissMeteoV2[2766:1029914] WARNING: GoogleAnalytics 3.10 void GAIUncaughtExceptionHandler(NSException *) (GAIUncaughtExceptionHandler.m:49): Uncaught exception: -[ApplicationController teads_presentModalViewController:animated:]: unrecognized selector sent to instance 0x145675c60
2015-11-06 16:12:39.119 SwissMeteoV2[2766:1029914] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ApplicationController teads_presentModalViewController:animated:]: unrecognized selector sent to instance 0x145675c60'
*** First throw call stack:
(0x1862b0f48 0x19ae63f80 0x1862b7c5c 0x1862b4c00 0x1861b8cac 0x1004f5b3c 0x100518a18 0x18bdbf330 0x18b9e8b5c 0x18b87685c 0x18bdc070c 0x18b8358b8 0x18b83263c 0x18b8746cc 0x18b873cc8 0x18b8444a4 0x18b84276c 0x186268544 0x186267fd8 0x186265cd8 0x186194ca0 0x1913d0088 0x18b8acffc 0x100088860 0x19b6b28b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

The point I don't understand is the fact it call the method on my ApplicationController. But the teads code is implemented 4 levels down in the hierarchy

**Comment by mArm-ch** [comment] 2015-11-13 09:17
Do you have some news ?

**Comment by mArm-ch** [comment] 2015-11-23 14:13
I still have the issue after updating to TeadsSDK 1.6.3.

Here's is an additional error i seen before the crash :
*CoreData: warning: Unable to load class named 'TeadsEventModel' for entity 'TeadsEventMod'.  Class not found, using default NSManagedObject instead.*

Then I have the error above.

**Comment by mArm-ch** [comment] 2015-12-04 13:27
Same issue with 1.6.4.

**Comment by ibrahimennafaa** [comment] 2015-12-04 13:29
Hi @mArm-ch ,

We are still trying to reproduce the issue. V1.6.4 was not about this indeed.

If you have any further information or any idea on what could cause this issue, please share here.

I'll keep you posted !

**Comment by mArm-ch** [comment] 2015-12-04 13:30
It's possible for me that you have a controller called "ApplicationController" in your SDK.
If it's the case, it probably conflict with the one in my application. I have a class called "ApplicationController"

**Comment by ibrahimennafaa** [comment] 2015-12-04 14:44
no ApplicationController class in the code ...

**Comment by mArm-ch** [comment] 2015-12-04 14:45
But the fact is here in the logs :

_-[ApplicationController teads_presentModalViewController:animated:]: unrecognized selector sent to instance 0x145675c60_

**Comment by ibrahimennafaa** [comment] 2015-12-04 14:55
teads_presentModalViewController:animated: is a function present in UIViewController+TeadsAdditions.h which is an extension. This extension class is imported in an internal .m file. I don't understand how it ends up being used by your own ViewController (ApplicationController) ...
That's what we are trying to understand

**Comment by ibrahimennafaa** [comment] 2015-12-04 15:10
Yes it is because we use an extension class called UIViewController+TeadsAdditions.h which add the function teads_presentModalViewController:animated:

**Comment by ibrahimennafaa** [comment] 2015-12-11 17:04
It should be fixed in v1.6.5 as we got rid of the class UIViewController+TeadsAdditions.h

Please let us know @mArm-ch so we can close this issue.

Thanks

**Comment by ibrahimennafaa** [comment] 2015-12-18 11:43
Hi @mArm-ch ,

Did you had time to test it ?

Thanks

**Comment by mArm-ch** [comment] 2015-12-18 12:30
No sorry, I will test this as soon as possible

*----------------------------------------*

*David Ansermot, **Technicien ES*
Senior web developer, iOS developer
iOS developer at ID Mobile SA
M : +41 78 611 41 17
david.ansermot@gmail.com
Profil LinkedIn <https://www.linkedin.com/in/davidansermot>

**Comment by mArm-ch** [comment] 2015-12-23 13:56
Hello.

I come back to you because I've tried to test the 1.6.6 SDK but it crashes
on the method "teadsVASTXMLPerformXPathQuery" (EXC_BAD_ACCESS)

*----------------------------------------*

*David Ansermot, **Technicien ES*
Senior web developer, iOS developer
iOS developer at ID Mobile SA
M : +41 78 611 41 17
david.ansermot@gmail.com
Profil LinkedIn <https://www.linkedin.com/in/davidansermot>

**Closed** 2016-07-21 08:08 UTC
